packages:
  - apps/*
  - packages/*

catalog:
  '@iconify-json/heroicons': ^1.2.3
  '@nuxt/eslint': 1.13.0
  '@nuxt/fonts': 0.13.0
  '@nuxt/icon': 2.2.1
  '@nuxt/ui': ^4.4.0
  '@pinia/nuxt': 0.11.3
  '@tresjs/post-processing': ^3.3.0
  '@types/three': ^0.182.0
  pinia: ^3.0.4

catalogMode: prefer

catalogs:
  build:
    tsdown: 0.20.3
    unplugin-vue: ^7.1.1
    vue-tsc: ^3.2.4
  eslint:
    eslint: ^9.36.0
  nuxt:
    '@nuxt/content': ^3.5.1
    '@nuxt/eslint': ^1.9.0
    nuxt: ^4.1.2
  three:
    '@tresjs/cientos': 5.4.0
    '@tresjs/core': ^5.5.0
    '@tresjs/eslint-config': ^1.5.1
    '@tresjs/leches': ^1.1.4
    '@tresjs/nuxt': ^5.3.0
    '@types/three': ^0.182.0
    three: ^0.182.0
  typescript:
    typescript: ^5.9.3
  vue:
    vue: ^3.5.27
    vue-router: ^5.0.2
