<script setup lang="ts">
/*
Auto-generated by @tresjs/cli. Do not edit.
Command: tres gltf public/levels/testbed.glb
Override the named slots from the parent instead; regenerating keeps your overrides.
*/
import type { Group, Mesh, MeshStandardMaterial } from 'three'
import { useGLTF } from '@tresjs/cientos'
import { ref, watch } from 'vue'

interface ModelNodes {
  Scene: Group
  Terrain: Mesh
  Rock_1_A_Color1: Mesh
  Rock_3_D_Color1: Mesh
  Rock_3_F_Color1: Mesh
  Tree_Bare_1_C_Color6: Mesh
  Tree_Cannopy_1_C_Color6001: Mesh
  Tree_Cannopy_1_C_Color6002: Mesh
  Tree_Cannopy_1_C_Color6003: Mesh
  Rock_3_D_Color1001: Mesh
  Rock_3_D_Color1002: Mesh
  Tree_Bare_1_C_Color6001: Mesh
  Tree_Bare_1_C_Color6002: Mesh
  Tree_Cannopy_1_C_Color6004: Mesh
  Tree_Cannopy_1_C_Color6005: Mesh
  Tree_Cannopy_1_C_Color6006: Mesh
  Tree_Bare_1_C_Color6003: Mesh
  Tree_Cannopy_1_C_Color6007: Mesh
  Tree_Cannopy_1_C_Color6008: Mesh
  Tree_Cannopy_1_C_Color6009: Mesh
  Tree_Cannopy_1_C_Color6010: Mesh
  Tree_Cannopy_1_C_Color6011: Mesh
  Tree_Cannopy_1_C_Color6012: Mesh
  Rock_3_D_Color1003: Mesh
  Rock_3_D_Color1004: Mesh
  Rock_3_D_Color1005: Mesh
}

interface ModelMaterials {
  'LandscapeMaterial': MeshStandardMaterial
  'forest': MeshStandardMaterial
  'forest.004': MeshStandardMaterial
}

const emit = defineEmits<{
  ready: [{ nodes: ModelNodes, materials: ModelMaterials }]
}>()

defineSlots<{
  Terrain?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Rock_1_A_Color1?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Rock_3_D_Color1?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Rock_3_F_Color1?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Tree_Cannopy_1_C_Color6001?: (props: { node: Mesh }) => any
  Tree_Cannopy_1_C_Color6002?: (props: { node: Mesh }) => any
  Tree_Cannopy_1_C_Color6003?: (props: { node: Mesh }) => any
  Tree_Bare_1_C_Color6?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Rock_3_D_Color1001?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Rock_3_D_Color1002?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Tree_Bare_1_C_Color6001?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Tree_Cannopy_1_C_Color6004?: (props: { node: Mesh }) => any
  Tree_Cannopy_1_C_Color6005?: (props: { node: Mesh }) => any
  Tree_Cannopy_1_C_Color6006?: (props: { node: Mesh }) => any
  Tree_Bare_1_C_Color6002?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Tree_Cannopy_1_C_Color6007?: (props: { node: Mesh }) => any
  Tree_Cannopy_1_C_Color6008?: (props: { node: Mesh }) => any
  Tree_Cannopy_1_C_Color6009?: (props: { node: Mesh }) => any
  Tree_Bare_1_C_Color6003?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Tree_Cannopy_1_C_Color6010?: (props: { node: Mesh }) => any
  Tree_Cannopy_1_C_Color6011?: (props: { node: Mesh }) => any
  Tree_Cannopy_1_C_Color6012?: (props: { node: Mesh }) => any
  Rock_3_D_Color1003?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Rock_3_D_Color1004?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
  Rock_3_D_Color1005?: (props: { node: Mesh, material: MeshStandardMaterial }) => any
}>()

const { state, nodes, materials, isLoading } = useGLTF<ModelNodes, ModelMaterials>('/levels/testbed.glb', { draco: true })

const isReady = ref(false)
watch(
  () => !isLoading.value
    && state.value !== null,
  (ready) => {
    if (!ready) {
      isReady.value = false
      return
    }
    if (isReady.value) { return }
    isReady.value = true
    emit('ready', { nodes: nodes.value, materials: materials.value })
  },
  { flush: 'post', immediate: true },
)

defineExpose({ nodes, materials, isReady })
</script>

<template>
  <TresGroup :dispose="null">
    <template v-if="!isLoading">
      <slot name="Terrain" :node="nodes.Terrain" :material="materials.LandscapeMaterial">
        <TresMesh :geometry="nodes.Terrain.geometry" :material="materials.LandscapeMaterial" />
      </slot>
      <slot name="Rock_1_A_Color1" :node="nodes.Rock_1_A_Color1" :material="materials.forest">
        <TresMesh :geometry="nodes.Rock_1_A_Color1.geometry" :material="materials.forest" :position="[-11.55, -4.68, 9.79]" :rotation="[0.18, 0, 0.31]" :scale="7.3" />
      </slot>
      <slot name="Rock_3_D_Color1" :node="nodes.Rock_3_D_Color1" :material="materials.forest">
        <TresMesh :geometry="nodes.Rock_3_D_Color1.geometry" :material="materials.forest" :position="[-1.56, -1.29, 15.39]" :rotation="[2, 1.04, 0.38]" :scale="[2.98, 2.98, 2.98]" />
      </slot>
      <slot name="Rock_3_F_Color1" :node="nodes.Rock_3_F_Color1" :material="materials.forest">
        <TresMesh :geometry="nodes.Rock_3_F_Color1.geometry" :material="materials.forest" :position="[-11.96, -6.17, 16.46]" :rotation="[0.09, -0.71, -0.76]" :scale="[3.9, 3.9, 3.9]" />
      </slot>
      <slot name="Tree_Bare_1_C_Color6" :node="nodes.Tree_Bare_1_C_Color6" :material="materials['forest.004']">
        <TresMesh :geometry="nodes.Tree_Bare_1_C_Color6.geometry" :material="materials['forest.004']" :position="[-18.89, 2.34, -1.52]" :rotation="[-0.01, -0.06, -0.08]">
          <slot name="Tree_Cannopy_1_C_Color6001" :node="nodes.Tree_Cannopy_1_C_Color6001">
            <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6001.geometry" />
          </slot>
          <slot name="Tree_Cannopy_1_C_Color6002" :node="nodes.Tree_Cannopy_1_C_Color6002">
            <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6002.geometry" />
          </slot>
          <slot name="Tree_Cannopy_1_C_Color6003" :node="nodes.Tree_Cannopy_1_C_Color6003">
            <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6003.geometry" />
          </slot>
        </TresMesh>
      </slot>
      <slot name="Rock_3_D_Color1001" :node="nodes.Rock_3_D_Color1001" :material="materials.forest">
        <TresMesh :geometry="nodes.Rock_3_D_Color1001.geometry" :material="materials.forest" :position="[-19.5, -1.22, 4.93]" :rotation="[2.68, 0.32, -0.27]" :scale="2.98" />
      </slot>
      <slot name="Rock_3_D_Color1002" :node="nodes.Rock_3_D_Color1002" :material="materials.forest">
        <TresMesh :geometry="nodes.Rock_3_D_Color1002.geometry" :material="materials.forest" :position="[-19.33, -2.06, 12.28]" :rotation="[1.9, 0.05, -0.51]" :scale="[5.98, 5.98, 5.98]" />
      </slot>
      <slot name="Tree_Bare_1_C_Color6001" :node="nodes.Tree_Bare_1_C_Color6001" :material="materials['forest.004']">
        <TresMesh :geometry="nodes.Tree_Bare_1_C_Color6001.geometry" :material="materials['forest.004']" :position="[-18.89, 2.34, -1.52]" :rotation="[-0.01, -0.06, -0.08]" />
      </slot>
      <slot name="Tree_Bare_1_C_Color6002" :node="nodes.Tree_Bare_1_C_Color6002" :material="materials['forest.004']">
        <TresMesh :geometry="nodes.Tree_Bare_1_C_Color6002.geometry" :material="materials['forest.004']" :position="[-1.45, 0.37, -24.44]" :rotation="[-3.13, -0.68, 3.08]">
          <slot name="Tree_Cannopy_1_C_Color6004" :node="nodes.Tree_Cannopy_1_C_Color6004">
            <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6004.geometry" :position="[0, 0, 0]" />
          </slot>
          <slot name="Tree_Cannopy_1_C_Color6005" :node="nodes.Tree_Cannopy_1_C_Color6005">
            <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6005.geometry" :position="[0, 0, 0]" />
          </slot>
          <slot name="Tree_Cannopy_1_C_Color6006" :node="nodes.Tree_Cannopy_1_C_Color6006">
            <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6006.geometry" :position="[0, 0, 0]" />
          </slot>
        </TresMesh>
      </slot>
      <slot name="Tree_Bare_1_C_Color6003" :node="nodes.Tree_Bare_1_C_Color6003" :material="materials['forest.004']">
        <TresMesh :geometry="nodes.Tree_Bare_1_C_Color6003.geometry" :material="materials['forest.004']" :position="[11.57, 6.09, 7.75]" :rotation="[-3.13, 0.11, 3.07]">
          <slot name="Tree_Cannopy_1_C_Color6007" :node="nodes.Tree_Cannopy_1_C_Color6007">
            <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6007.geometry" />
          </slot>
          <slot name="Tree_Cannopy_1_C_Color6008" :node="nodes.Tree_Cannopy_1_C_Color6008">
            <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6008.geometry" />
          </slot>
          <slot name="Tree_Cannopy_1_C_Color6009" :node="nodes.Tree_Cannopy_1_C_Color6009">
            <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6009.geometry" />
          </slot>
        </TresMesh>
      </slot>
      <slot name="Tree_Cannopy_1_C_Color6010" :node="nodes.Tree_Cannopy_1_C_Color6010">
        <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6010.geometry" :position="[-18.86, 2.38, -0.68]" :rotation="[0.2, 0, -0.09]" />
      </slot>
      <slot name="Tree_Cannopy_1_C_Color6011" :node="nodes.Tree_Cannopy_1_C_Color6011">
        <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6011.geometry" :position="[-18.86, 2.38, -0.68]" :rotation="[0.2, 0, -0.09]" />
      </slot>
      <slot name="Tree_Cannopy_1_C_Color6012" :node="nodes.Tree_Cannopy_1_C_Color6012">
        <TresMesh :geometry="nodes.Tree_Cannopy_1_C_Color6012.geometry" :position="[-18.86, 2.38, -0.68]" :rotation="[0.2, 0, -0.09]" />
      </slot>
      <slot name="Rock_3_D_Color1003" :node="nodes.Rock_3_D_Color1003" :material="materials.forest">
        <TresMesh :geometry="nodes.Rock_3_D_Color1003.geometry" :material="materials.forest" :position="[-0.7, -1.34, 17.01]" :rotation="[-2.28, 0.56, -2.84]" :scale="[1.97, 1.97, 1.97]" />
      </slot>
      <slot name="Rock_3_D_Color1004" :node="nodes.Rock_3_D_Color1004" :material="materials.forest">
        <TresMesh :geometry="nodes.Rock_3_D_Color1004.geometry" :material="materials.forest" :position="[-21.2, -1.03, 4.2]" :rotation="[2.76, 0.86, -1.91]" :scale="[1.85, 1.85, 1.85]" />
      </slot>
      <slot name="Rock_3_D_Color1005" :node="nodes.Rock_3_D_Color1005" :material="materials.forest">
        <TresMesh :geometry="nodes.Rock_3_D_Color1005.geometry" :material="materials.forest" :position="[-18.14, -3.8, 15.48]" :rotation="[-2.87, -0.55, -1.69]" :scale="[3.65, 3.65, 3.65]" />
      </slot>
    </template>
  </TresGroup>
</template>
